<a href="https://colab.research.google.com/github/JayeshDabholkar/NPS_Data_Analytics/blob/main/NPS_Data_Analytics.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
#NPS - Net Promoter Score

<img src="https://drive.google.com/uc?id=1-u8e-v_90JdikorKsKzBM-JJqoRtzsN8">


In [ ]:
#NPS - Net Promoter Score

<img src="https://drive.google.com/uc?id=1KPIYlaN68vlL99iApaF5QbeBoyT24-Eu">


NPS Case Study

https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Dataset link

In [2]:
!gdown 1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK

Downloading...
From: https://drive.google.com/uc?id=1c0ClC8SrPwJq5rrkyMKyPn80nyHcFikK
To: /content/survey.txt
100% 2.55k/2.55k [00:00<00:00, 3.12MB/s]


In [3]:
!ls

sample_data  survey.txt


In [6]:
scores = np.loadtxt('survey.txt')
scores

array([ 7., 10.,  5., ...,  5.,  9., 10.])

In [8]:
scores.mean()

7.250214224507284

In [1]:
import numpy as np

In [9]:
#Promoters

promoters_scores = scores[ scores > 8 ]
promoters_scores

array([10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,
        9.,  9.,  9.,  9., 10., 10.,  9., 10.,  9., 10.,  9.,  9., 10.,
       10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10., 10.,  9.,
       10.,  9., 10.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,
       10.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10.,
       10.,  9., 10.,  9.,  9., 10.,  9.,  9., 10.,  9.,  9.,  9.,  9.,
        9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9.,  9., 10., 10.,  9., 10.,
       10., 10., 10.,  9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9., 10.,  9., 10., 10., 10.,  9.,  9., 10., 10.,  9.,
        9.,  9.,  9., 10.,  9.,  9.,  9.,  9., 10., 10.,  9.,  9.,  9.,
       10.,  9.,  9.,  9.,  9.,  9., 10.,  9.,  9.,  9., 10.,  9., 10.,
       10.,  9.,  9.,  9.,  9., 10.,  9., 10.,  9.,  9.,  9.,  9., 10.,
        9., 10.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9.,  9

In [10]:
#Detractors

detractors_scores = scores[ scores < 7 ]
detractors_scores

array([5., 4., 4., 5., 1., 5., 5., 1., 4., 5., 4., 4., 4., 5., 1., 4., 1.,
       4., 1., 5., 5., 1., 1., 4., 1., 5., 4., 1., 1., 4., 1., 5., 1., 4.,
       4., 1., 1., 1., 1., 1., 1., 1., 4., 1., 1., 5., 5., 5., 4., 4., 1.,
       4., 1., 4., 1., 5., 1., 1., 5., 4., 4., 4., 4., 1., 4., 5., 4., 4.,
       1., 1., 5., 5., 1., 5., 1., 5., 5., 4., 5., 4., 1., 1., 1., 1., 4.,
       1., 4., 4., 5., 4., 1., 1., 1., 1., 5., 4., 5., 5., 4., 1., 5., 1.,
       4., 4., 1., 1., 1., 4., 4., 5., 5., 4., 5., 5., 5., 1., 4., 1., 5.,
       5., 1., 5., 1., 1., 5., 5., 4., 4., 1., 4., 4., 4., 1., 1., 4., 4.,
       4., 5., 5., 1., 1., 4., 1., 4., 1., 4., 1., 4., 1., 4., 1., 5., 4.,
       4., 5., 1., 4., 5., 5., 5., 1., 5., 4., 1., 1., 5., 5., 5., 4., 5.,
       4., 4., 1., 4., 4., 4., 4., 5., 1., 5., 5., 1., 4., 4., 5., 1., 1.,
       4., 5., 5., 5., 1., 4., 5., 5., 4., 1., 5., 5., 5., 1., 1., 5., 5.,
       1., 1., 1., 4., 5., 5., 4., 4., 4., 5., 1., 4., 1., 4., 5., 4., 5.,
       5., 1., 5., 1., 5.

In [11]:
promoters_count = len(promoters_scores)
promoters_count

609

In [12]:
detractors_count = len(detractors_scores)
detractors_count

332

In [13]:
total_count = len(scores)
total_count

1167

In [14]:
percent_promoters = (promoters_count/total_count) * 100


In [15]:
percent_detractors = (detractors_count/total_count) * 100


In [17]:
nps = percent_promoters - percent_detractors


In [18]:
round(nps, 2)

23.74



<img src="https://drive.google.com/uc?id=1FYgRM2XmJs4Rv-l8CCUn_aXcyw7GfZlp">




After referring above range of NPS scores we can conculde that this sample data has GOOD NPS score, also NPS score depends on the category of an organisation/industry.
Please see below attachment for reference



<img src="https://drive.google.com/uc?id=1vyRFRpHMC7LJ6MNB_K7Mih7pR_m7t-_A">
